// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Register.API.Data;

#nullable disable

namespace Register.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230730074321_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Register.API.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ad3b4d2f-5afc-4535-a353-4f6961d8c6f1"),
                            Code = 25465,
                            Name = "Futbolka"
                        },
                        new
                        {
                            Id = new Guid("1deaec52-a945-4167-9e70-61ccddf9581e"),
                            Code = 123445,
                            Name = "Kuylak"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
